### ISSUE TITLE
Improvement: Synchronized Recall func

### ISSUE THREAD

**Issue by Kane67** [alaingilbert/ogame#19]
Hello All,

I would like to know if you find it useful to have a function to recall all fleets with Missions [park] to return at specific time or have a fleet Saver that return all the fleets at a specific time. I use this sometimes to have all my resources available to check once a day to build or develop my planets.

I already have working logic coded in Java and Groovy. I am now transcript it into GO, because I am learning GO atm.

When finished I can push the result and you can obtain what ever you want.

best regards

**Comment by flashover** [comment]
Hello Kane,

I'm just a regular user of this fantastic library, I have created a few patches to the source code which I still need to open Pull Requests for. So take my opinions with a grain of salt :)

I was thinking about developing something similar to this. Instead of Java / Groovy I'd be using PHP as it's my preferred scripting language. I doubt that I ever will be publishing my user scripts though ....

Also I'm not sure if this should be in the library / API or rather as a user-script. Providing the target return-time, providing FleetID or just perform it on the largest fleets you have in {harvest,park,colonize}-mission, put a sleep function on it until the recall-time, shouldn't be hundreds of lines of code. So in that regard maybe for you it's fine if you want to have this use case where you sharpen your Go-skills but that it might not get included in the regular sources here.

Happy to see you here :)

**Comment by Kane67** [comment]
Thank you @flashover for your nice answer. I thaught about your words and yes its a userscript task, which should not need in the API. Sorry I mixed things up here and keep the API clean and clear is much better.

I am Java and C++ programmer and worked on C# Projects the last two years, now I want to make something different and look into other Language to get experienced with. I left working with PHP since 2004 where I started to use C++ as my main language. I will close this and will publish the function as userscript later. I don't know if there is any community around this GO API on discord.

Have a nice day

**Comment by alaingilbert** [comment]
@Kane67 The discord community is a good idea.
It would be nice to be able to share some scripts made with the library.
Maybe we could use the Wiki to list all the gists made by users.
The closest thing that I know of for now is the community built around this (totally not maintained by me) website: https://www.ogame.ninja/ https://gist.github.com/ogame-ninja https://discord.gg/DAVetf6

**Comment by alaingilbert** [comment]
I made a discord server for this library: https://discord.gg/sDV8AB
So we can start a small community of ogame developers, and help each others.

**Comment by jc01rho** [comment]
> I made a discord server for this library: https://discord.gg/sDV8AB
> So we can start a small community of ogame developers, and help each others.

invite might be expired. please re-create for permenant period :p

**Comment by apg258** [comment]
@jc01rho This should work.

https://discord.gg/WU8UAG3

**Comment by alaingilbert** [comment]
You're right, my previous link had an expiration time of 1 day.
Here is a permanent one: https://discord.gg/4dZtZpz
