### ISSUE TITLE
Static Handler for /cdn/* not working propably. Problems on Pages: marketplace, traderOverview, premium and shop Pull Request #80 should fix this issue

### ISSUE THREAD

**Issue by 0xE232FE** [alaingilbert/ogame#79]
The Marketplace doesn't work with the current handler because needed scripts are not loaded propably
Functions like sort, next-prev -page, filters aren't working atm.

I fixed it for me by commenting out the Part "//Copy the original HTTP headers to our client" compare with my code.

```
// GetStaticHandler ...
func GetStaticHandler(c echo.Context) error {
	bot := c.Get("bot").(*OGame)

	newURL := bot.serverURL + c.Request().URL.String()
	req, err := http.NewRequest("GET", newURL, nil)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, ErrorResp(500, err.Error()))
	}
	req.Header.Add("Accept-Encoding", "gzip, deflate, br")
	resp, err := bot.Client.Do(req)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, ErrorResp(500, err.Error()))
	}
	defer resp.Body.Close()
	body, _, err := readBody(resp)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, ErrorResp(500, err.Error()))
	}
	/*
		// Copy the original HTTP headers to our client
		for k, vv := range resp.Header { // duplicate headers are acceptable in HTTP spec, so add all of them individually: https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
			k = http.CanonicalHeaderKey(k)
			for _, v := range vv {
				c.Response().Header().Add(k, v)
			}
		}
	*/

	if strings.Contains(c.Request().URL.String(), ".xml") {
		body = replaceHostname(bot, prepareHostname(c.Request().TLS, c.Request().Host), body)
		return c.Blob(http.StatusOK, "application/xml", body)
	}

	contentType := http.DetectContentType(body)
	if strings.Contains(newURL, ".css") {
		contentType = "text/css"
	} else if strings.Contains(newURL, ".js") {
		contentType = "text/javascript"
	} else if strings.Contains(newURL, ".gif") {
		contentType = "image/gif"
	}
	return c.Blob(http.StatusOK, contentType, body)
}
```

![cdn_not_loaded_on_anypage](https://user-images.githubusercontent.com/21330562/90311754-f0b9f680-defe-11ea-8c5a-0bddec7cad85.png)

**Comment by flashover** [comment]
Hi

I created that function, but in my code it is slightly different. Probably because of my bad Git skills it's not in sync anymore with Master branch.

The block of code you disabled was put there for two reasons (IIRC):
1) Copy caching headers from origin
2) Copy the content-type headers from origin

Why disabling makes it better for you I don't understand yet.

I see the same behavior on my side for "sort, next-prev -page, filters" in Marketplace. When I used the debugging tools I found that for one URL is being called:

> /game/index.php?page=ingame&component=marketplace&tab=buying&action=fetchBuyingItems..............

It returns a JSON blob (with content-type application/html....):

`marketplace.urlFetchBuyingItems = \"https:\\/\\/s123-nl.ogame.gameforge.com\\/game\\/index.php?page=ingame&component=marketplace&tab=buying&action=fetchBuyingItems&token=xyz234j234xyz&ajax=1\";\n</script>\n"`

So the URL for "sort, next-prev -page, filters" probably uses that URL from variable `marketplace.urlFetchBuyingItems` instead of using (in your case) the https://127.0.0.1:8080/`

Maybe the problem is with `func replaceHostname` not picking up your API-hostname correctly. And then when you click the "sort, next-prev -page, filters" it calls the wrong URL. I don't know fully yet. Will look at it later.

**Comment by 0xE232FE** [comment]
**Market Problem** _(solved otherwise)_
Oh yes, you are completly right!!! 

The Marketlinks have to be double Escaped, cause of jscript usage!

Check my fork for this [here](https://github.com/0xE232FE/ogame.mod/blob/200fd3d595dda8a3c0e00e3131242ca6a3bed1aa/handlers.go#L900)


** load /cdn/* Problem  ***
Okay I looked into it now. So if it is only about the Cache-Control this is no problem we can just copy the original cache control instead of copy all header fields!

This code fixes the Problem and copy the Cache Key from the Origin request if this is that what you supose to do.

```
	// Copy the original HTTP headers to our client
	for k, vv := range resp.Header { // duplicate headers are acceptable in HTTP spec, so add all of them individually: https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
		k = http.CanonicalHeaderKey(k)
		for _, v := range vv {
			if k == "Cache-Control" {
				c.Response().Header().Add(k, v)
			}
		}
	}
```

**Comment by 0xE232FE** [comment]
#80 should fix this
